### ISSUE TITLE
/bin/sh: /var/acme/renew.sh: Permission denied

### ISSUE THREAD

**Issue by nlfthl** [helsinki-systems/sophos-xgs-letsencrypt#1]
Hi there,

cant tell you how relieved I was when I found someone had done a "fix" for Sophos lacking interest in listening to customers.
Unfortunately it isnt working for me.
I followed the howto from your blogpost, unfortunately I get a permission denied issue. I am on SFOS 20.0.0.
Im not so good with scripting, but from what Ive been able to determine, the permission denied actually comes from acme.sh, because the mount-command isnt executed beforehand, and at that point I was just left without any idea.
Any help with this would be greatly appreciated

**Comment by nlfthl** [comment]
After looking into S01acme it became clear that for the initial run of renew.sh I needed to remount /var ... All mood now.

**Comment by Scriptkiddi** [comment]
sorry was sick the last couple, so its working for you now?

**Comment by nlfthl** [comment]
Yeah, if I remount /var to 'exec' before the initial start of renew.sh its running fine.
I suppose that could be built into the script better, but for me its working like this.
Thanks!
