### ISSUE TITLE
Working - but not for all Public IPS

### ISSUE THREAD

**Issue by Ercan-Gueven** [helsinki-systems/sophos-xgs-letsencrypt#2]
I have many Public IPs on my XGS  - not all for public Access via 80 or 443. On some the script is working, on other i got a timeout error.
"Timeout during connect (likely firewall problem)"

Any Idea how i can temporary handle this? The log is not showing anything relevant. Maybe its a nat issue?

Any help would be greatly appreciated.

Thank you in advance

**Comment by Scriptkiddi** [comment]
Are the dns records pointing to the correct ip?

**Comment by Ercan-Gueven** [comment]
Yes i got several Public Ips
xxx.xxx.xxx.114 (not used with dns)
xxx.xxx.xxx.115 (works -> two domains)
xxx.xxx.xxx.116 (does not work -> 2 domains)
xxx.xxx.xxx.117 (works -> 3 domains)

Greetings

**Comment by Ercan-Gueven** [comment]
Issue has been resolved. I configured new "temporary" Webrules for the not working IPs. Thank you very much
